const {
  VITE_EMPMANAGE_CLOUDINARY_CLOUD_NAME,
  VITE_EMPMANAGE_CLOUDINARY_API_KEY,
  VITE_EMPMANAGE_CLOUDINARY_API_SECRET,
  VITE_EMPMANAGE_CLOUDINARY_UPLOAD_PRESET,
} = import.meta.env;

const cloudinaryConfig = {
  cloudName: VITE_EMPMANAGE_CLOUDINARY_CLOUD_NAME,
  apiKey: VITE_EMPMANAGE_CLOUDINARY_API_KEY,
  apiSecret: VITE_EMPMANAGE_CLOUDINARY_API_SECRET,
  uploadPreset: VITE_EMPMANAGE_CLOUDINARY_UPLOAD_PRESET,
};
export { cloudinaryConfig };
