const {
  VITE_EMPMANAGE_CLOUDINARY_CLOUD_NAME,
  VITE_EMPMANAGE_CLOUDINARY_API_KEY,
  VITE_EMPMANAGE_CLOUDINARY_API_SECRET,
} = import.meta.env;

const cloudinaryConfig = {
  cloudName: VITE_EMPMANAGE_CLOUDINARY_CLOUD_NAME,
  apiKey: VITE_EMPMANAGE_CLOUDINARY_API_KEY,
  apiSecret: VITE_EMPMANAGE_CLOUDINARY_API_SECRET,
};
export { cloudinaryConfig };
